import {
  CustomDetailDemographic,
  CustomDetailGarmentGroup,
  CustomDetailOption,
  CustomDetailSelectionGroup,
} from "../types";

export type Demographic = CustomDetailDemographic;
export type GarmentGroup = CustomDetailGarmentGroup;
export type SelectionGroup = CustomDetailSelectionGroup;

export const CUSTOM_DETAIL_SELECTION_GROUPS: CustomDetailSelectionGroup[] = [
  "shirt_construction",
  "shirt_pockets",
  "dress_construction",
  "dress_pockets",
  "neck_design",
  "standard_shorts_fastening",
  "standard_shorts_pockets",
  "bum_shorts_fastening",
  "bum_shorts_pockets",
  "trouser_fastening",
  "trouser_pockets",
  "skirt_length",
  "skirt_pockets",
];

export const SEED_CUSTOM_DETAIL_CATALOG: CustomDetailOption[] = [

  // SHIRT LENGTH AND SLEEVE LENGTH
{
    id: "shirt_std_short",
    label: "Standard Length Shirt, Short Sleeve",
    description: "Shirt length is up to crotch level; one-piece shirt.",
    priceCents: 6500,
    garmentGroup: "shirt",
    eligibleDemographics: ["male", "unisex"],
    selectionGroup: "shirt_construction",
    displayOrder: 0,
    required: true,
    active: true,
    allowMultiple: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
{
    id: "shirt_std_midlong",
    label: "Standard Length Shirt, Mid-Long Sleeve",
    description: "Shirt length is up to crotch level; one-piece shirt.",
    priceCents: 7000,
    garmentGroup: "shirt",
    eligibleDemographics: ["male", "unisex"],
    selectionGroup: "shirt_construction",
    displayOrder: 0,
    required: true,
    active: true,
    allowMultiple: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
{
    id: "shirt_long_short",
    label: "Long Length Shirt, Short Sleeve",
    description: "Shirt length extends from knee level toward the ankle; one-piece shirt.",
    priceCents: 7000,
    garmentGroup: "shirt",
    eligibleDemographics: ["male", "unisex"],
    selectionGroup: "shirt_construction",
    displayOrder: 0,
    required: true,
    active: true,
    allowMultiple: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
{
    id: "shirt_long_midlong",
    label: "Long Length Shirt, Mid-Long Sleeve",
    description: "Shirt length extends from knee level toward the ankle; one-piece shirt.",
    priceCents: 7500,
    garmentGroup: "shirt",
    eligibleDemographics: ["male", "unisex"],
    selectionGroup: "shirt_construction",
    displayOrder: 0,
    required: true,
    active: true,
    allowMultiple: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },

  // SHIRT POCKETS
{
    id: "shirt_pocket_1",
    label: "With 1 Chest Pocket",
    description: "One pocket on the left or right side of the chest.",
    priceCents: 0,
    garmentGroup: "shirt",
    eligibleDemographics: ["male", "unisex"],
    selectionGroup: "shirt_pockets",
    displayOrder: 0,
    required: true,
    active: true,
    allowMultiple: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
{
    id: "shirt_pocket_2",
    label: "With 2 Chest Pockets",
    description: "One pocket on each side of the chest.",
    priceCents: 0,
    garmentGroup: "shirt",
    eligibleDemographics: ["male", "unisex"],
    selectionGroup: "shirt_pockets",
    displayOrder: 0,
    required: true,
    active: true,
    allowMultiple: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
{
    id: "shirt_pocket_0",
    label: "No Pockets",
    description: "No chest pockets.",
    priceCents: 0,
    garmentGroup: "shirt",
    eligibleDemographics: ["male", "unisex"],
    selectionGroup: "shirt_pockets",
    displayOrder: 0,
    required: true,
    active: true,
    allowMultiple: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },

  // DRESS LENGTH AND SLEEVE LENGTH — LADIES
{
    id: "dress_std_sleeveless",
    label: "Standard Length, Sleeveless / Over Shoulder",
    description: "Dress length extends from the waist to crotch level; one-piece dress.",
    priceCents: 7000,
    garmentGroup: "dress",
    eligibleDemographics: ["female", "unisex"],
    selectionGroup: "dress_construction",
    displayOrder: 0,
    required: true,
    active: true,
    allowMultiple: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
{
    id: "dress_std_short",
    label: "Standard Length, Short Sleeve",
    description: "Dress length extends from the waist to crotch level; one-piece dress.",
    priceCents: 7000,
    garmentGroup: "dress",
    eligibleDemographics: ["female", "unisex"],
    selectionGroup: "dress_construction",
    displayOrder: 0,
    required: true,
    active: true,
    allowMultiple: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
{
    id: "dress_std_midlong",
    label: "Standard Length, Mid (3-Quarter) / Long Sleeve",
    description: "Dress length extends from the waist to crotch level; one-piece dress.",
    priceCents: 7500,
    garmentGroup: "dress",
    eligibleDemographics: ["female", "unisex"],
    selectionGroup: "dress_construction",
    displayOrder: 0,
    required: true,
    active: true,
    allowMultiple: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
{
    id: "dress_long_sleeveless",
    label: "Long Length, Sleeveless / Over Shoulder",
    description: "Dress length extends from knee level toward the ankle; one-piece dress.",
    priceCents: 7500,
    garmentGroup: "dress",
    eligibleDemographics: ["female", "unisex"],
    selectionGroup: "dress_construction",
    displayOrder: 0,
    required: true,
    active: true,
    allowMultiple: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
{
    id: "dress_long_short",
    label: "Long Length, Short Sleeve",
    description: "Dress length extends from knee level toward the ankle; one-piece dress.",
    priceCents: 7500,
    garmentGroup: "dress",
    eligibleDemographics: ["female", "unisex"],
    selectionGroup: "dress_construction",
    displayOrder: 0,
    required: true,
    active: true,
    allowMultiple: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
{
    id: "dress_long_midlong",
    label: "Long Length, Mid (3-Quarter) / Long Sleeve",
    description: "Dress length extends from knee level toward the ankle; one-piece dress.",
    priceCents: 8000,
    garmentGroup: "dress",
    eligibleDemographics: ["female", "unisex"],
    selectionGroup: "dress_construction",
    displayOrder: 0,
    required: true,
    active: true,
    allowMultiple: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },

  // DRESS POCKETS
{
    id: "dress_pocket_1",
    label: "With 1 Side Pocket",
    description: "One pocket on the left or right side seam.",
    priceCents: 0,
    garmentGroup: "dress",
    eligibleDemographics: ["female", "unisex"],
    selectionGroup: "dress_pockets",
    displayOrder: 0,
    required: true,
    active: true,
    allowMultiple: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
{
    id: "dress_pocket_multi",
    label: "With Pocket(s)",
    description: "Specify the number and preferred position of the pockets.",
    priceCents: 0,
    garmentGroup: "dress",
    eligibleDemographics: ["female", "unisex"],
    selectionGroup: "dress_pockets",
    displayOrder: 0,
    required: true,
    active: true,
    allowMultiple: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
{
    id: "dress_pocket_0",
    label: "No Pockets",
    description: "No dress pockets.",
    priceCents: 0,
    garmentGroup: "dress",
    eligibleDemographics: ["female", "unisex"],
    selectionGroup: "dress_pockets",
    displayOrder: 0,
    required: true,
    active: true,
    allowMultiple: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },

  // NECK DESIGN
{
    id: "neck_no_round",
    label: "No Collar, Round Neck",
    description: "Collarless design with a round neckline.",
    priceCents: 0,
    garmentGroup: "neck",
    eligibleDemographics: ["male", "female", "unisex"],
    selectionGroup: "neck_design",
    displayOrder: 0,
    required: true,
    active: true,
    allowMultiple: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
{
    id: "neck_no_v",
    label: "No Collar, V-Shaped Neck",
    description: "Collarless design with a V-shaped neckline.",
    priceCents: 0,
    garmentGroup: "neck",
    eligibleDemographics: ["male", "female", "unisex"],
    selectionGroup: "neck_design",
    displayOrder: 0,
    required: true,
    active: true,
    allowMultiple: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
{
    id: "neck_no_u",
    label: "No Collar, U or Square-Shaped Neck",
    description: "Collarless design with a U or square neckline.",
    priceCents: 0,
    garmentGroup: "neck",
    eligibleDemographics: ["male", "female", "unisex"],
    selectionGroup: "neck_design",
    displayOrder: 0,
    required: true,
    active: true,
    allowMultiple: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
{
    id: "neck_vert_round",
    label: "Vertical Collar, Round Neck",
    description: "Vertical collar (mandarin style) with a round neckline.",
    priceCents: 0,
    garmentGroup: "neck",
    eligibleDemographics: ["male", "female", "unisex"],
    selectionGroup: "neck_design",
    displayOrder: 0,
    required: true,
    active: true,
    allowMultiple: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
{
    id: "neck_vert_v",
    label: "Vertical Collar, V-Shaped Neck",
    description: "Vertical collar with a V-shaped neckline.",
    priceCents: 0,
    garmentGroup: "neck",
    eligibleDemographics: ["male", "female", "unisex"],
    selectionGroup: "neck_design",
    displayOrder: 0,
    required: true,
    active: true,
    allowMultiple: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
{
    id: "neck_vert_u",
    label: "Vertical Collar, U or Square-Shaped Neck",
    description: "Vertical collar with a U or square neckline.",
    priceCents: 0,
    garmentGroup: "neck",
    eligibleDemographics: ["male", "female", "unisex"],
    selectionGroup: "neck_design",
    displayOrder: 0,
    required: true,
    active: true,
    allowMultiple: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
{
    id: "neck_flat_round",
    label: "Flat Collar, Round Neck",
    description: "Flat lay collar with a round neckline.",
    priceCents: 0,
    garmentGroup: "neck",
    eligibleDemographics: ["male", "female", "unisex"],
    selectionGroup: "neck_design",
    displayOrder: 0,
    required: true,
    active: true,
    allowMultiple: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
{
    id: "neck_flat_v",
    label: "Flat Collar, V-Shaped Neck",
    description: "Flat lay collar with a V-shaped neckline.",
    priceCents: 0,
    garmentGroup: "neck",
    eligibleDemographics: ["male", "female", "unisex"],
    selectionGroup: "neck_design",
    displayOrder: 0,
    required: true,
    active: true,
    allowMultiple: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
{
    id: "neck_flat_u",
    label: "Flat Collar, U or Square-Shaped Neck",
    description: "Flat lay collar with a U or square neckline.",
    priceCents: 0,
    garmentGroup: "neck",
    eligibleDemographics: ["male", "female", "unisex"],
    selectionGroup: "neck_design",
    displayOrder: 0,
    required: true,
    active: true,
    allowMultiple: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },

  // STANDARD LEG SHORTS — NIKKA
{
    id: "shorts_std_rope",
    label: "With Rope",
    description: "Shorts ending just above the knee with a drawstring rope.",
    priceCents: 7000,
    garmentGroup: "standard_shorts",
    eligibleDemographics: ["male", "unisex"],
    selectionGroup: "standard_shorts_fastening",
    displayOrder: 0,
    required: true,
    active: true,
    allowMultiple: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
{
    id: "shorts_std_elastic",
    label: "With Elastic Band",
    description: "Shorts ending just above the knee with an elastic waistband.",
    priceCents: 7500,
    garmentGroup: "standard_shorts",
    eligibleDemographics: ["male", "unisex"],
    selectionGroup: "standard_shorts_fastening",
    displayOrder: 0,
    required: true,
    active: true,
    allowMultiple: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
{
    id: "shorts_std_belt",
    label: "With Belt Holder",
    description: "Shorts ending just above the knee with belt loops.",
    priceCents: 7500,
    garmentGroup: "standard_shorts",
    eligibleDemographics: ["male", "unisex"],
    selectionGroup: "standard_shorts_fastening",
    displayOrder: 0,
    required: true,
    active: true,
    allowMultiple: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
{
    id: "shorts_std_pocket_regular",
    label: "Regular Side Waist Pockets",
    description: "Standard side pockets on the waist.",
    priceCents: 0,
    garmentGroup: "standard_shorts",
    eligibleDemographics: ["male", "unisex"],
    selectionGroup: "standard_shorts_pockets",
    displayOrder: 0,
    required: true,
    active: true,
    allowMultiple: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
{
    id: "shorts_std_pocket_back",
    label: "Back Pocket",
    description: "Pocket on the back of the shorts.",
    priceCents: 0,
    garmentGroup: "standard_shorts",
    eligibleDemographics: ["male", "unisex"],
    selectionGroup: "standard_shorts_pockets",
    displayOrder: 0,
    required: true,
    active: true,
    allowMultiple: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
{
    id: "shorts_std_pocket_none",
    label: "No Pockets",
    description: "No pockets on the shorts.",
    priceCents: 0,
    garmentGroup: "standard_shorts",
    eligibleDemographics: ["male", "unisex"],
    selectionGroup: "standard_shorts_pockets",
    displayOrder: 0,
    required: true,
    active: true,
    allowMultiple: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },

  // BUM / LEG SHORTS
{
    id: "bum_rope",
    label: "With Rope",
    description: "Shorts ending just below the crotch at lap level with a drawstring rope.",
    priceCents: 7000,
    garmentGroup: "bum_shorts",
    eligibleDemographics: ["male", "female", "unisex"],
    selectionGroup: "bum_shorts_fastening",
    displayOrder: 0,
    required: true,
    active: true,
    allowMultiple: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
{
    id: "bum_elastic",
    label: "With Elastic Band",
    description: "Shorts ending just below the crotch at lap level with an elastic waistband.",
    priceCents: 7500,
    garmentGroup: "bum_shorts",
    eligibleDemographics: ["male", "female", "unisex"],
    selectionGroup: "bum_shorts_fastening",
    displayOrder: 0,
    required: true,
    active: true,
    allowMultiple: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
{
    id: "bum_belt",
    label: "With Belt Holder",
    description: "Shorts ending just below the crotch at lap level with belt loops.",
    priceCents: 7500,
    garmentGroup: "bum_shorts",
    eligibleDemographics: ["male", "female", "unisex"],
    selectionGroup: "bum_shorts_fastening",
    displayOrder: 0,
    required: true,
    active: true,
    allowMultiple: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
{
    id: "bum_pocket_regular",
    label: "Regular Side Waist Pockets",
    description: "Standard side pockets on the waist.",
    priceCents: 0,
    garmentGroup: "bum_shorts",
    eligibleDemographics: ["male", "female", "unisex"],
    selectionGroup: "bum_shorts_pockets",
    displayOrder: 0,
    required: true,
    active: true,
    allowMultiple: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
{
    id: "bum_pocket_back",
    label: "Back Pocket",
    description: "Pocket on the back of the shorts.",
    priceCents: 0,
    garmentGroup: "bum_shorts",
    eligibleDemographics: ["male", "female", "unisex"],
    selectionGroup: "bum_shorts_pockets",
    displayOrder: 0,
    required: true,
    active: true,
    allowMultiple: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
{
    id: "bum_pocket_none",
    label: "No Pockets",
    description: "No pockets on the shorts.",
    priceCents: 0,
    garmentGroup: "bum_shorts",
    eligibleDemographics: ["male", "female", "unisex"],
    selectionGroup: "bum_shorts_pockets",
    displayOrder: 0,
    required: true,
    active: true,
    allowMultiple: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },

  // LEG PANTS — TROUSERS
{
    id: "trouser_rope",
    label: "With Rope",
    description: "Full-length trousers extending to the ankle with a drawstring rope.",
    priceCents: 7500,
    garmentGroup: "trousers",
    eligibleDemographics: ["male", "unisex"],
    selectionGroup: "trouser_fastening",
    displayOrder: 0,
    required: true,
    active: true,
    allowMultiple: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
{
    id: "trouser_elastic",
    label: "With Elastic Band",
    description: "Full-length trousers extending to the ankle with an elastic waistband.",
    priceCents: 8000,
    garmentGroup: "trousers",
    eligibleDemographics: ["male", "unisex"],
    selectionGroup: "trouser_fastening",
    displayOrder: 0,
    required: true,
    active: true,
    allowMultiple: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
{
    id: "trouser_belt",
    label: "With Belt Holder",
    description: "Full-length trousers extending to the ankle with belt loops.",
    priceCents: 8000,
    garmentGroup: "trousers",
    eligibleDemographics: ["male", "unisex"],
    selectionGroup: "trouser_fastening",
    displayOrder: 0,
    required: true,
    active: true,
    allowMultiple: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
{
    id: "trouser_pocket_regular",
    label: "Regular Side Waist Pockets",
    description: "Standard side pockets on the waist.",
    priceCents: 0,
    garmentGroup: "trousers",
    eligibleDemographics: ["male", "unisex"],
    selectionGroup: "trouser_pockets",
    displayOrder: 0,
    required: true,
    active: true,
    allowMultiple: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
{
    id: "trouser_pocket_back",
    label: "Back Pocket",
    description: "Pocket on the back of the trousers.",
    priceCents: 0,
    garmentGroup: "trousers",
    eligibleDemographics: ["male", "unisex"],
    selectionGroup: "trouser_pockets",
    displayOrder: 0,
    required: true,
    active: true,
    allowMultiple: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
{
    id: "trouser_pocket_none",
    label: "No Pockets",
    description: "No pockets on the trousers.",
    priceCents: 0,
    garmentGroup: "trousers",
    eligibleDemographics: ["male", "unisex"],
    selectionGroup: "trouser_pockets",
    displayOrder: 0,
    required: true,
    active: true,
    allowMultiple: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },

  // SKIRTS — LADIES
{
    id: "skirt_std",
    label: "Standard Length, Above Knee",
    description: "Skirt ending just above the knee.",
    priceCents: 7500,
    garmentGroup: "skirt",
    eligibleDemographics: ["female", "unisex"],
    selectionGroup: "skirt_length",
    displayOrder: 0,
    required: true,
    active: true,
    allowMultiple: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
{
    id: "skirt_long",
    label: "Long Length",
    description: "Skirt extending from knee level toward the ankle.",
    priceCents: 8000,
    garmentGroup: "skirt",
    eligibleDemographics: ["female", "unisex"],
    selectionGroup: "skirt_length",
    displayOrder: 0,
    required: true,
    active: true,
    allowMultiple: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
{
    id: "skirt_pocket_1",
    label: "With 1 Side Pocket",
    description: "One pocket on the left or right side seam.",
    priceCents: 0,
    garmentGroup: "skirt",
    eligibleDemographics: ["female", "unisex"],
    selectionGroup: "skirt_pockets",
    displayOrder: 0,
    required: true,
    active: true,
    allowMultiple: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
{
    id: "skirt_pocket_2",
    label: "With 2 Side Pockets",
    description: "One pocket on each side seam.",
    priceCents: 0,
    garmentGroup: "skirt",
    eligibleDemographics: ["female", "unisex"],
    selectionGroup: "skirt_pockets",
    displayOrder: 0,
    required: true,
    active: true,
    allowMultiple: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
{
    id: "skirt_pocket_none",
    label: "No Pockets",
    description: "No skirt pockets.",
    priceCents: 0,
    garmentGroup: "skirt",
    eligibleDemographics: ["female", "unisex"],
    selectionGroup: "skirt_pockets",
    displayOrder: 0,
    required: true,
    active: true,
    allowMultiple: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },

];
