import {
  CustomDetailDemographic,
  CustomDetailGarmentGroup,
  CustomDetailOption,
  CustomDetailSelectionGroup,
} from "../types";

export type Demographic = CustomDetailDemographic;
export type GarmentGroup = CustomDetailGarmentGroup;
export type SelectionGroup = CustomDetailSelectionGroup;

export const CUSTOM_DETAIL_SELECTION_GROUPS: CustomDetailSelectionGroup[] = [
  "shirt_construction",
  "shirt_pockets",
  "dress_construction",
  "dress_pockets",
  "neck_design",
  "standard_shorts_fastening",
  "standard_shorts_pockets",
  "bum_shorts_fastening",
  "bum_shorts_pockets",
  "trouser_fastening",
  "trouser_pockets",
  "skirt_length",
  "skirt_pockets",
];

export const CUSTOM_DETAIL_SELECTION_GROUP_ORDER: Readonly<
  Record<CustomDetailSelectionGroup, number>
> = {
  shirt_construction: 10,
  shirt_pockets: 20,
  dress_construction: 30,
  dress_pockets: 40,
  neck_design: 50,
  standard_shorts_fastening: 60,
  standard_shorts_pockets: 70,
  bum_shorts_fastening: 80,
  bum_shorts_pockets: 90,
  trouser_fastening: 100,
  trouser_pockets: 110,
  skirt_length: 120,
  skirt_pockets: 130,
};

export const CUSTOM_DETAIL_OPTION_ORDER: Readonly<Record<string, number>> = {
  shirt_std_short: 10,
  shirt_std_midlong: 20,
  shirt_long_short: 30,
  shirt_long_midlong: 40,
  shirt_pocket_1: 10,
  shirt_pocket_2: 20,
  shirt_pocket_0: 30,
  dress_std_sleeveless: 10,
  dress_std_short: 20,
  dress_std_midlong: 30,
  dress_long_sleeveless: 40,
  dress_long_short: 50,
  dress_long_midlong: 60,
  dress_pocket_1: 10,
  dress_pocket_multi: 20,
  dress_pocket_0: 30,
  neck_no_round: 10,
  neck_no_v: 20,
  neck_no_u: 30,
  neck_vert_round: 40,
  neck_vert_v: 50,
  neck_vert_u: 60,
  neck_flat_round: 70,
  neck_flat_v: 80,
  neck_flat_u: 90,
  shorts_std_rope: 10,
  shorts_std_elastic: 20,
  shorts_std_belt: 30,
  shorts_std_pocket_regular: 10,
  shorts_std_pocket_back: 20,
  shorts_std_pocket_none: 30,
  bum_rope: 10,
  bum_elastic: 20,
  bum_belt: 30,
  bum_pocket_regular: 10,
  bum_pocket_back: 20,
  bum_pocket_none: 30,
  trouser_rope: 10,
  trouser_elastic: 20,
  trouser_belt: 30,
  trouser_pocket_regular: 10,
  trouser_pocket_back: 20,
  trouser_pocket_none: 30,
  skirt_std: 10,
  skirt_long: 20,
  skirt_pocket_1: 10,
  skirt_pocket_2: 20,
  skirt_pocket_none: 30,
};

export const CUSTOM_DETAIL_SELECTION_GROUP_PRESENTATION: Readonly<
  Record<
    CustomDetailSelectionGroup,
    { title: string; description?: string }
  >
> = {
  shirt_construction: { title: "Shirt Length and Sleeve Length" },
  shirt_pockets: { title: "Shirt Pockets" },
  dress_construction: {
    title: "Dress Length and Sleeve Length (Ladies)",
  },
  dress_pockets: { title: "Dress Pockets" },
  neck_design: { title: "Neck Design" },
  standard_shorts_fastening: {
    title: "Standard Leg Shorts (Nikka) - Fastening",
    description: "Just above the knee",
  },
  standard_shorts_pockets: {
    title: "Standard Leg Shorts (Nikka) - Pockets",
    description: "Just above the knee",
  },
  bum_shorts_fastening: {
    title: "Bum (Leg) Shorts - Fastening",
    description: "Just below the crotch at lap level",
  },
  bum_shorts_pockets: {
    title: "Bum (Leg) Shorts - Pockets",
    description: "Just below the crotch at lap level",
  },
  trouser_fastening: {
    title: "Leg Pants (Trouser) - Fastening",
    description: "Up to the ankle",
  },
  trouser_pockets: {
    title: "Leg Pants (Trouser) - Pockets",
    description: "Up to the ankle",
  },
  skirt_length: {
    title: "Skirts (Ladies) - Length",
  },
  skirt_pockets: {
    title: "Skirts (Ladies) - Pockets",
  },
};

export const ADDITIONAL_CLOTHES_COST_SECTION_ORDER = [
  "shirt_additional",
  "dress_additional",
  "neck_additional",
  "trouser_additional",
  "standard_shorts_additional",
  "bum_shorts_additional",
  "skirt_additional",
  "personalized_additional",
] as const;

export type AdditionalClothesCostSection =
  (typeof ADDITIONAL_CLOTHES_COST_SECTION_ORDER)[number];

export const ADDITIONAL_CLOTHES_COST_SECTION_RANK: Readonly<
  Record<AdditionalClothesCostSection, number>
> = Object.fromEntries(
  ADDITIONAL_CLOTHES_COST_SECTION_ORDER.map((section, index) => [
    section,
    (index + 1) * 10,
  ]),
) as Record<AdditionalClothesCostSection, number>;

export const SEED_CUSTOM_DETAIL_CATALOG: CustomDetailOption[] = [

  // SHIRT LENGTH AND SLEEVE LENGTH
{
    id: "shirt_std_short",
    label: "Standard Length Shirt, Short Sleeve",
    description: "Shirt length is up to crotch level; one-piece shirt.",
    priceCents: 6500,
    garmentGroup: "shirt",
    eligibleDemographics: ["male", "unisex"],
    selectionGroup: "shirt_construction",
    displayOrder: 0,
    required: true,
    active: true,
    allowMultiple: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
{
    id: "shirt_std_midlong",
    label: "Standard Length Shirt, Mid-Long Sleeve",
    description: "Shirt length is up to crotch level; one-piece shirt.",
    priceCents: 7000,
    garmentGroup: "shirt",
    eligibleDemographics: ["male", "unisex"],
    selectionGroup: "shirt_construction",
    displayOrder: 0,
    required: true,
    active: true,
    allowMultiple: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
{
    id: "shirt_long_short",
    label: "Long Length Shirt, Short Sleeve",
    description: "Shirt length extends from knee level toward the ankle; one-piece shirt.",
    priceCents: 7000,
    garmentGroup: "shirt",
    eligibleDemographics: ["male", "unisex"],
    selectionGroup: "shirt_construction",
    displayOrder: 0,
    required: true,
    active: true,
    allowMultiple: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
{
    id: "shirt_long_midlong",
    label: "Long Length Shirt, Mid-Long Sleeve",
    description: "Shirt length extends from knee level toward the ankle; one-piece shirt.",
    priceCents: 7500,
    garmentGroup: "shirt",
    eligibleDemographics: ["male", "unisex"],
    selectionGroup: "shirt_construction",
    displayOrder: 0,
    required: true,
    active: true,
    allowMultiple: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },

  // SHIRT POCKETS
{
    id: "shirt_pocket_1",
    label: "With 1 Chest Pocket",
    description: "One pocket on the left or right side of the chest.",
    priceCents: 0,
    garmentGroup: "shirt",
    eligibleDemographics: ["male", "unisex"],
    selectionGroup: "shirt_pockets",
    displayOrder: 0,
    required: true,
    active: true,
    allowMultiple: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
{
    id: "shirt_pocket_2",
    label: "With 2 Chest Pockets",
    description: "One pocket on each side of the chest.",
    priceCents: 0,
    garmentGroup: "shirt",
    eligibleDemographics: ["male", "unisex"],
    selectionGroup: "shirt_pockets",
    displayOrder: 0,
    required: true,
    active: true,
    allowMultiple: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
{
    id: "shirt_pocket_0",
    label: "No Pockets",
    description: "No chest pockets.",
    priceCents: 0,
    garmentGroup: "shirt",
    eligibleDemographics: ["male", "unisex"],
    selectionGroup: "shirt_pockets",
    displayOrder: 0,
    required: true,
    active: true,
    allowMultiple: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },

  // DRESS LENGTH AND SLEEVE LENGTH — LADIES
{
    id: "dress_std_sleeveless",
    label: "Standard Length, Sleeveless / Over Shoulder",
    description: "Dress length extends from the waist to crotch level; one-piece dress.",
    priceCents: 7000,
    garmentGroup: "dress",
    eligibleDemographics: ["female", "unisex"],
    selectionGroup: "dress_construction",
    displayOrder: 0,
    required: true,
    active: true,
    allowMultiple: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
{
    id: "dress_std_short",
    label: "Standard Length, Short Sleeve",
    description: "Dress length extends from the waist to crotch level; one-piece dress.",
    priceCents: 7000,
    garmentGroup: "dress",
    eligibleDemographics: ["female", "unisex"],
    selectionGroup: "dress_construction",
    displayOrder: 0,
    required: true,
    active: true,
    allowMultiple: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
{
    id: "dress_std_midlong",
    label: "Standard Length, Mid (3-Quarter) / Long Sleeve",
    description: "Dress length extends from the waist to crotch level; one-piece dress.",
    priceCents: 7500,
    garmentGroup: "dress",
    eligibleDemographics: ["female", "unisex"],
    selectionGroup: "dress_construction",
    displayOrder: 0,
    required: true,
    active: true,
    allowMultiple: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
{
    id: "dress_long_sleeveless",
    label: "Long Length, Sleeveless / Over Shoulder",
    description: "Dress length extends from knee level toward the ankle; one-piece dress.",
    priceCents: 7500,
    garmentGroup: "dress",
    eligibleDemographics: ["female", "unisex"],
    selectionGroup: "dress_construction",
    displayOrder: 0,
    required: true,
    active: true,
    allowMultiple: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
{
    id: "dress_long_short",
    label: "Long Length, Short Sleeve",
    description: "Dress length extends from knee level toward the ankle; one-piece dress.",
    priceCents: 7500,
    garmentGroup: "dress",
    eligibleDemographics: ["female", "unisex"],
    selectionGroup: "dress_construction",
    displayOrder: 0,
    required: true,
    active: true,
    allowMultiple: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
{
    id: "dress_long_midlong",
    label: "Long Length, Mid (3-Quarter) / Long Sleeve",
    description: "Dress length extends from knee level toward the ankle; one-piece dress.",
    priceCents: 8000,
    garmentGroup: "dress",
    eligibleDemographics: ["female", "unisex"],
    selectionGroup: "dress_construction",
    displayOrder: 0,
    required: true,
    active: true,
    allowMultiple: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },

  // DRESS POCKETS
{
    id: "dress_pocket_1",
    label: "With 1 Side Pocket",
    description: "One pocket on the left or right side seam.",
    priceCents: 0,
    garmentGroup: "dress",
    eligibleDemographics: ["female", "unisex"],
    selectionGroup: "dress_pockets",
    displayOrder: 0,
    required: true,
    active: true,
    allowMultiple: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
{
    id: "dress_pocket_multi",
    label: "With Pocket(s)",
    description: "Specify the number and preferred position of the pockets.",
    priceCents: 0,
    garmentGroup: "dress",
    eligibleDemographics: ["female", "unisex"],
    selectionGroup: "dress_pockets",
    displayOrder: 0,
    required: true,
    active: true,
    allowMultiple: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
{
    id: "dress_pocket_0",
    label: "No Pockets",
    description: "No dress pockets.",
    priceCents: 0,
    garmentGroup: "dress",
    eligibleDemographics: ["female", "unisex"],
    selectionGroup: "dress_pockets",
    displayOrder: 0,
    required: true,
    active: true,
    allowMultiple: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },

  // NECK DESIGN
{
    id: "neck_no_round",
    label: "No Collar, Round Neck",
    description: "Collarless design with a round neckline.",
    priceCents: 0,
    garmentGroup: "neck",
    eligibleDemographics: ["male", "female", "unisex"],
    selectionGroup: "neck_design",
    displayOrder: 0,
    required: true,
    active: true,
    allowMultiple: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
{
    id: "neck_no_v",
    label: "No Collar, V-Shaped Neck",
    description: "Collarless design with a V-shaped neckline.",
    priceCents: 0,
    garmentGroup: "neck",
    eligibleDemographics: ["male", "female", "unisex"],
    selectionGroup: "neck_design",
    displayOrder: 0,
    required: true,
    active: true,
    allowMultiple: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
{
    id: "neck_no_u",
    label: "No Collar, U or Square-Shaped Neck",
    description: "Collarless design with a U or square neckline.",
    priceCents: 0,
    garmentGroup: "neck",
    eligibleDemographics: ["male", "female", "unisex"],
    selectionGroup: "neck_design",
    displayOrder: 0,
    required: true,
    active: true,
    allowMultiple: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
{
    id: "neck_vert_round",
    label: "Vertical Collar, Round Neck",
    description: "Vertical collar (mandarin style) with a round neckline.",
    priceCents: 0,
    garmentGroup: "neck",
    eligibleDemographics: ["male", "female", "unisex"],
    selectionGroup: "neck_design",
    displayOrder: 0,
    required: true,
    active: true,
    allowMultiple: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
{
    id: "neck_vert_v",
    label: "Vertical Collar, V-Shaped Neck",
    description: "Vertical collar with a V-shaped neckline.",
    priceCents: 0,
    garmentGroup: "neck",
    eligibleDemographics: ["male", "female", "unisex"],
    selectionGroup: "neck_design",
    displayOrder: 0,
    required: true,
    active: true,
    allowMultiple: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
{
    id: "neck_vert_u",
    label: "Vertical Collar, U or Square-Shaped Neck",
    description: "Vertical collar with a U or square neckline.",
    priceCents: 0,
    garmentGroup: "neck",
    eligibleDemographics: ["male", "female", "unisex"],
    selectionGroup: "neck_design",
    displayOrder: 0,
    required: true,
    active: true,
    allowMultiple: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
{
    id: "neck_flat_round",
    label: "Flat Collar, Round Neck",
    description: "Flat lay collar with a round neckline.",
    priceCents: 0,
    garmentGroup: "neck",
    eligibleDemographics: ["male", "female", "unisex"],
    selectionGroup: "neck_design",
    displayOrder: 0,
    required: true,
    active: true,
    allowMultiple: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
{
    id: "neck_flat_v",
    label: "Flat Collar, V-Shaped Neck",
    description: "Flat lay collar with a V-shaped neckline.",
    priceCents: 0,
    garmentGroup: "neck",
    eligibleDemographics: ["male", "female", "unisex"],
    selectionGroup: "neck_design",
    displayOrder: 0,
    required: true,
    active: true,
    allowMultiple: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
{
    id: "neck_flat_u",
    label: "Flat Collar, U or Square-Shaped Neck",
    description: "Flat lay collar with a U or square neckline.",
    priceCents: 0,
    garmentGroup: "neck",
    eligibleDemographics: ["male", "female", "unisex"],
    selectionGroup: "neck_design",
    displayOrder: 0,
    required: true,
    active: true,
    allowMultiple: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },

  // STANDARD LEG SHORTS — NIKKA
{
    id: "shorts_std_rope",
    label: "With Rope",
    description: "Shorts ending just above the knee with a drawstring rope.",
    priceCents: 7000,
    garmentGroup: "standard_shorts",
    eligibleDemographics: ["male", "unisex"],
    selectionGroup: "standard_shorts_fastening",
    displayOrder: 0,
    required: true,
    active: true,
    allowMultiple: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
{
    id: "shorts_std_elastic",
    label: "With Elastic Band",
    description: "Shorts ending just above the knee with an elastic waistband.",
    priceCents: 7500,
    garmentGroup: "standard_shorts",
    eligibleDemographics: ["male", "unisex"],
    selectionGroup: "standard_shorts_fastening",
    displayOrder: 0,
    required: true,
    active: true,
    allowMultiple: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
{
    id: "shorts_std_belt",
    label: "With Belt Holder",
    description: "Shorts ending just above the knee with belt loops.",
    priceCents: 7500,
    garmentGroup: "standard_shorts",
    eligibleDemographics: ["male", "unisex"],
    selectionGroup: "standard_shorts_fastening",
    displayOrder: 0,
    required: true,
    active: true,
    allowMultiple: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
{
    id: "shorts_std_pocket_regular",
    label: "Regular Side Waist Pockets",
    description: "Standard side pockets on the waist.",
    priceCents: 0,
    garmentGroup: "standard_shorts",
    eligibleDemographics: ["male", "unisex"],
    selectionGroup: "standard_shorts_pockets",
    displayOrder: 0,
    required: true,
    active: true,
    allowMultiple: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
{
    id: "shorts_std_pocket_back",
    label: "Back Pocket",
    description: "Pocket on the back of the shorts.",
    priceCents: 0,
    garmentGroup: "standard_shorts",
    eligibleDemographics: ["male", "unisex"],
    selectionGroup: "standard_shorts_pockets",
    displayOrder: 0,
    required: true,
    active: true,
    allowMultiple: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
{
    id: "shorts_std_pocket_none",
    label: "No Pockets",
    description: "No pockets on the shorts.",
    priceCents: 0,
    garmentGroup: "standard_shorts",
    eligibleDemographics: ["male", "unisex"],
    selectionGroup: "standard_shorts_pockets",
    displayOrder: 0,
    required: true,
    active: true,
    allowMultiple: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },

  // BUM / LEG SHORTS
{
    id: "bum_rope",
    label: "With Rope",
    description: "Shorts ending just below the crotch at lap level with a drawstring rope.",
    priceCents: 7000,
    garmentGroup: "bum_shorts",
    eligibleDemographics: ["male", "female", "unisex"],
    selectionGroup: "bum_shorts_fastening",
    displayOrder: 0,
    required: true,
    active: true,
    allowMultiple: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
{
    id: "bum_elastic",
    label: "With Elastic Band",
    description: "Shorts ending just below the crotch at lap level with an elastic waistband.",
    priceCents: 7500,
    garmentGroup: "bum_shorts",
    eligibleDemographics: ["male", "female", "unisex"],
    selectionGroup: "bum_shorts_fastening",
    displayOrder: 0,
    required: true,
    active: true,
    allowMultiple: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
{
    id: "bum_belt",
    label: "With Belt Holder",
    description: "Shorts ending just below the crotch at lap level with belt loops.",
    priceCents: 7500,
    garmentGroup: "bum_shorts",
    eligibleDemographics: ["male", "female", "unisex"],
    selectionGroup: "bum_shorts_fastening",
    displayOrder: 0,
    required: true,
    active: true,
    allowMultiple: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
{
    id: "bum_pocket_regular",
    label: "Regular Side Waist Pockets",
    description: "Standard side pockets on the waist.",
    priceCents: 0,
    garmentGroup: "bum_shorts",
    eligibleDemographics: ["male", "female", "unisex"],
    selectionGroup: "bum_shorts_pockets",
    displayOrder: 0,
    required: true,
    active: true,
    allowMultiple: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
{
    id: "bum_pocket_back",
    label: "Back Pocket",
    description: "Pocket on the back of the shorts.",
    priceCents: 0,
    garmentGroup: "bum_shorts",
    eligibleDemographics: ["male", "female", "unisex"],
    selectionGroup: "bum_shorts_pockets",
    displayOrder: 0,
    required: true,
    active: true,
    allowMultiple: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
{
    id: "bum_pocket_none",
    label: "No Pockets",
    description: "No pockets on the shorts.",
    priceCents: 0,
    garmentGroup: "bum_shorts",
    eligibleDemographics: ["male", "female", "unisex"],
    selectionGroup: "bum_shorts_pockets",
    displayOrder: 0,
    required: true,
    active: true,
    allowMultiple: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },

  // LEG PANTS — TROUSERS
{
    id: "trouser_rope",
    label: "With Rope",
    description: "Full-length trousers extending to the ankle with a drawstring rope.",
    priceCents: 7500,
    garmentGroup: "trousers",
    eligibleDemographics: ["male", "unisex"],
    selectionGroup: "trouser_fastening",
    displayOrder: 0,
    required: true,
    active: true,
    allowMultiple: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
{
    id: "trouser_elastic",
    label: "With Elastic Band",
    description: "Full-length trousers extending to the ankle with an elastic waistband.",
    priceCents: 8000,
    garmentGroup: "trousers",
    eligibleDemographics: ["male", "unisex"],
    selectionGroup: "trouser_fastening",
    displayOrder: 0,
    required: true,
    active: true,
    allowMultiple: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
{
    id: "trouser_belt",
    label: "With Belt Holder",
    description: "Full-length trousers extending to the ankle with belt loops.",
    priceCents: 8000,
    garmentGroup: "trousers",
    eligibleDemographics: ["male", "unisex"],
    selectionGroup: "trouser_fastening",
    displayOrder: 0,
    required: true,
    active: true,
    allowMultiple: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
{
    id: "trouser_pocket_regular",
    label: "Regular Side Waist Pockets",
    description: "Standard side pockets on the waist.",
    priceCents: 0,
    garmentGroup: "trousers",
    eligibleDemographics: ["male", "unisex"],
    selectionGroup: "trouser_pockets",
    displayOrder: 0,
    required: true,
    active: true,
    allowMultiple: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
{
    id: "trouser_pocket_back",
    label: "Back Pocket",
    description: "Pocket on the back of the trousers.",
    priceCents: 0,
    garmentGroup: "trousers",
    eligibleDemographics: ["male", "unisex"],
    selectionGroup: "trouser_pockets",
    displayOrder: 0,
    required: true,
    active: true,
    allowMultiple: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
{
    id: "trouser_pocket_none",
    label: "No Pockets",
    description: "No pockets on the trousers.",
    priceCents: 0,
    garmentGroup: "trousers",
    eligibleDemographics: ["male", "unisex"],
    selectionGroup: "trouser_pockets",
    displayOrder: 0,
    required: true,
    active: true,
    allowMultiple: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },

  // SKIRTS — LADIES
{
    id: "skirt_std",
    label: "Standard Length, Above Knee",
    description: "Skirt ending just above the knee.",
    priceCents: 7500,
    garmentGroup: "skirt",
    eligibleDemographics: ["female", "unisex"],
    selectionGroup: "skirt_length",
    displayOrder: 0,
    required: true,
    active: true,
    allowMultiple: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
{
    id: "skirt_long",
    label: "Long Length",
    description: "Skirt extending from knee level toward the ankle.",
    priceCents: 8000,
    garmentGroup: "skirt",
    eligibleDemographics: ["female", "unisex"],
    selectionGroup: "skirt_length",
    displayOrder: 0,
    required: true,
    active: true,
    allowMultiple: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
{
    id: "skirt_pocket_1",
    label: "With 1 Side Pocket",
    description: "One pocket on the left or right side seam.",
    priceCents: 0,
    garmentGroup: "skirt",
    eligibleDemographics: ["female", "unisex"],
    selectionGroup: "skirt_pockets",
    displayOrder: 0,
    required: true,
    active: true,
    allowMultiple: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
{
    id: "skirt_pocket_2",
    label: "With 2 Side Pockets",
    description: "One pocket on each side seam.",
    priceCents: 0,
    garmentGroup: "skirt",
    eligibleDemographics: ["female", "unisex"],
    selectionGroup: "skirt_pockets",
    displayOrder: 0,
    required: true,
    active: true,
    allowMultiple: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
{
    id: "skirt_pocket_none",
    label: "No Pockets",
    description: "No skirt pockets.",
    priceCents: 0,
    garmentGroup: "skirt",
    eligibleDemographics: ["female", "unisex"],
    selectionGroup: "skirt_pockets",
    displayOrder: 0,
    required: true,
    active: true,
    allowMultiple: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },

];
